project:
  type: website
  output-dir: docs
website:
  title: "lostinbooks.club"
  site-url: https://www.lostinbooks.club
  favicon: "favicon.ico"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anarinsk
      #- icon: twitter
      #  href: https://twitter.com
  body-header: "google_analytics.html"
format:
  html:
    theme: [flatly, anari-custom.scss] 
      #dark: [vapor, theme-dark.scss, anari-custom.scss]  
      #light: [vapor, theme.scss, anari-custom.scss]
  #css: styles.css



